# Funções do Numpy

Somando Valores

In [1]:
import numpy as np

In [3]:
Lista = np.arange(0, 10)

In [4]:
Lista

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
Lista.sum()

45

#### <br>Converter lista comum para um np.array

In [9]:
lista_comum = [10, 20, 30]

In [11]:
type(lista_comum)

list

In [13]:
lista_np = np.array(lista_comum)

In [15]:
type(lista_np)

numpy.ndarray

#### <br><br>Tipos de criação de arrays

In [16]:
print(np.zeros(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [17]:
print(np.ones((5, 5)))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [7]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
print(np.diag(np.array([1, 2, 3, 4])))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [9]:
# O método linspace( linearly spaced vector) retorna um número de valores
# igualmente distribuídos no intervalo específicado
print(np.linspace(0, 10, 15))

[  0.           0.71428571   1.42857143   2.14285714   2.85714286
   3.57142857   4.28571429   5.           5.71428571   6.42857143
   7.14285714   7.85714286   8.57142857   9.28571429  10.        ]


In [10]:
print(np.linspace(10, 15, 3))

[ 10.   12.5  15. ]


#### <br><br>Forçando type do array

In [11]:
x = np.array([[24, 76], [35, 89]])

In [12]:
x

array([[24, 76],
       [35, 89]])

In [13]:
print(x.dtype)

int64


In [14]:
x = np.array(x, dtype=np.float64)

In [15]:
x

array([[ 24.,  76.],
       [ 35.,  89.]])

In [16]:
print(x.dtype)

float64


#### <br>Numero de Dimensões

In [17]:
x.ndim

2

#### <br>Retornando o Produto

In [18]:
Lista.prod()

0

#### <br>Soma Acumulada

In [19]:
Lista.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

#### <br>Função para retornar resposta de igualdade

In [20]:
Lista2 = np.arange(11, 20)

In [21]:
Lista2

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.array_equal(Lista, Lista2)

False

#### <br>Função round()

In [23]:
c = np.array([1.5, 2.5, 3.5, 4.5])

In [24]:
c

array([ 1.5,  2.5,  3.5,  4.5])

In [25]:
c = c.round()

In [26]:
c

array([ 2.,  2.,  4.,  4.])

<br>

In [27]:
d = np.array([1.5, 2.5, 3.5, 4.5])

In [28]:
d

array([ 1.5,  2.5,  3.5,  4.5])

In [29]:
d = np.around(d)

In [30]:
d

array([ 2.,  2.,  4.,  4.])

#### <br>Função de Cópia

In [31]:
d = np.arange(6)

In [32]:
d

array([0, 1, 2, 3, 4, 5])

In [33]:
e = d.flatten()

In [34]:
e

array([0, 1, 2, 3, 4, 5])

In [35]:
x = e.copy()

In [36]:
x

array([0, 1, 2, 3, 4, 5])

#### <br>Repetir os Elementos de um Array

In [37]:
# Repetir cada elemento no numero do parametro
np.repeat(x, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [38]:
# Repetir o array no numero que esta no parametro
np.tile(x,2)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

#### <br>Concatenar Arrays

In [39]:
Lista

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
Lista2

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
conc = np.concatenate((Lista, Lista2), axis=0)

In [42]:
conc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

#### <br> Estatística com Numpy

In [43]:
# Média é o valor que aponta para onde mais se concentram os dados de uma distribiução
Lista.mean()

4.5

<br>

In [44]:
# O desvio padrão mostra o quanto de varialçao ou "dispesão" existe em 
# relação á média (ou valor esperado).
# Um baico desvio padrão indica que os dados tendem a estar próximos da média
# Um descvio padrão alto indica que os dados estão espalhados por uma gama de valores
Lista.std()

2.8722813232690143

<br>

In [45]:
# Variâmmcoa de uma variável aleatório é uma medida de sua dispersão
# estatística,, indicando " o qual longe" em geral os seus valores se encontram do valor esperado:
Lista.var()

8.25

#### <br>Fatiamento de Lista

In [2]:
arr = np.arange(0,50, 3)

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [4]:
arr[3]

9

In [5]:
arr[2:5]

array([ 6,  9, 12])

In [6]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
dd